apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  labels:
    {{- include "kube-stats-exporter.labels" . | nindent 4 }}
  name: {{ include "kube-stats-exporter.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/metrics
      - nodes/stats
      - nodes/proxy
      - nodes
    verbs:
      - get
      - list
