apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-stats-exporter.fullname" . }}
  labels:
    {{- include "kube-stats-exporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kube-stats-exporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kube-stats-exporter.serviceAccountName" . }}
    namespace: {{ $.Release.Namespace }}
