{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "kube-stats-exporter.fullname" $ }}
  labels:
    {{- include "kube-stats-exporter.labels" . | nindent 4 }}
    {{- if or .Values.serviceMonitor.labels .labels }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - port: metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    honorLabels: true
    path: /metrics
  jobLabel: "{{ .Release.Name }}"
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kube-stats-exporter.name" $ }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
