apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-stats-exporter.fullname" . }}
  labels:
    {{- include "kube-stats-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: kube-stats-exporter
    {{- include "kube-stats-exporter.selectorLabels" . | nindent 4 }}
